### ISSUE TITLE
Saut de version

### ISSUE THREAD

**Issue by Alexiscomete** [Sylicium/Discord-bot-settings-API#1]
Avec le commit https://github.com/Sylicium/Discord-bot-settings-API/commit/b44bb129efc4a1e238aea3cd8e6b2449d88114dc
On passe de la version 2.1.2 à 3.1.1
Il manque au minimum 2 versions !
v3.0.0 et v3.1.0 !!!

_~~Cette faille de sécurité est bien sûr très importante~~_ :octocat:

Il faut trouver une solution

**Comment by Sylicium** [comment]
C'est parce que j'avais update logger.js sur d'autres projets mais oublié de le synchroniser sur celui là, d'où l'énorme saut de version x)
T'en fait pas c'est normal owo
